Constrain ci_reporter dependency to < 2.0
ci_reporter 2.0 was just released and it breaks minitest-chef-handler
as follows:

```
LoadError: cannot load such file -- ci/reporter/minitest
```

Until we're fully compatible with ci_reporter 2, this should resolve
the issue.